/* version.spec.ts
 *
 * The build stamp is generated by scripts/stamp-version.mjs before every
 * start, build and test run, and shown in the corner of every page. This
 * guards the shape of what that script writes: a silently malformed stamp
 * would otherwise only be noticed by reading the corner of a deployed page.
 */

import { describe, it, expect } from 'vitest';
import { APP_VERSION } from './version';

describe('APP_VERSION', () => {
  it('is a package version plus a UTC build timestamp', () => {
    expect(APP_VERSION).toMatch(/^\d+\.\d+\.\d+\+\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/);
  });

  it('carries a timestamp that is a real, recent moment', () => {
    const [, stamp] = APP_VERSION.split('+');
    const stampedAt = new Date(`${stamp}:00Z`);

    expect(Number.isNaN(stampedAt.getTime())).toBe(false);
    // Stamped by the pretest hook moments ago, so anything older than a day
    // means the hook did not run and the stamp is stale.
    const ageMs = Date.now() - stampedAt.getTime();
    expect(ageMs).toBeLessThan(24 * 60 * 60 * 1000);
    expect(ageMs).toBeGreaterThan(-5 * 60 * 1000);
  });
});
