/* stamp-version.mjs
 *
 * Writes `src/app/version.ts` with the build version the footer shows: the
 * version field from package.json plus a UTC build timestamp, for example
 * `0.0.1+2026-09-20T08:42`. The timestamp is what makes it useful — it says
 * which build is live, which a hand-bumped version number alone does not.
 *
 * Carried over from ilc-members-manager (scripts/stamp-version.ts), rewritten
 * as ESM to match this repo's other scripts and to avoid a ts-node dependency.
 *
 * Run it:
 *   pnpm run stamp-version
 *
 * It also runs on its own before `start`, `build` and `test:once`, so the
 * generated file is always present and always current. It is gitignored: it is
 * a build product, not source. `firebase.json` runs `pnpm run build` as its
 * hosting predeploy step, so every deploy carries a fresh stamp.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(repoRoot, 'package.json'), 'utf8'));

// A compact UTC timestamp: YYYY-MM-DDTHH:MM. UTC so that builds made in
// different timezones still sort and compare sensibly.
const now = new Date();
const pad = (n) => String(n).padStart(2, '0');
const timestamp =
  `${now.getUTCFullYear()}-${pad(now.getUTCMonth() + 1)}-${pad(now.getUTCDate())}` +
  `T${pad(now.getUTCHours())}:${pad(now.getUTCMinutes())}`;

const version = `${pkg.version}+${timestamp}`;
const outFile = join(repoRoot, 'src/app/version.ts');

writeFileSync(
  outFile,
  `/* Auto-generated by scripts/stamp-version.mjs — do not edit, and do not commit.
 * Regenerate with \`pnpm run stamp-version\`.
 */
export const APP_VERSION = '${version}';
`,
  'utf8',
);

console.log(`Stamped version ${version} into src/app/version.ts`);
